# workaround for buffer overflow issue, ref https://github.com/travis-ci/travis-ci/issues/5227
os: linux
arch:
 - amd64
 - ppc64le
addons:
  hosts:
    - myhostname
  hostname: myhostname

language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
